version: "2.3"
services:
  plasma-contracts:
    environment:
      - REMOTE_URL=https://rinkeby.infura.io/v3/<infura_api_key>
      - DEPLOYER_PRIVATEKEY=<deployer_privkey>
      - MAINTAINER_PRIVATEKEY=<maintainer_privkey>
      - AUTHORITY_PRIVATEKEY=<authority_privkey>
    healthcheck:
      # Takes roughly 10 minutes to deploy all contracts, so check every minute up to 15 minutes
      interval: 60s
      timeout: 10s
      retries: 15

  childchain:
    environment:
      - ETHEREUM_RPC_URL=https://rinkeby.infura.io/v3/<infura_api_key>
      - ETHEREUM_WS_RPC_URL=wss://rinkeby.infura.io/ws/v3/<infura_api_key>

  watcher:
    environment:
      - ETHEREUM_RPC_URL=https://rinkeby.infura.io/v3/<infura_api_key>
      - ETHEREUM_WS_RPC_URL=wss://rinkeby.infura.io/ws/v3/<infura_api_key>

  geth:
    # We don't need geth but docker-compose doesn't support overrides to remove or disable a service
    # So here we set `--dev.period 0` to minimize resource utilization.
    entrypoint: /bin/sh -c "apk add curl && geth --dev --dev.period 0 --rpc --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcport=8545"
