# this is an override to our usual docker-compose.yml which enables cabbage integration tests to run against a
# test-friendly setup of our services
version: "2.3"
services:
  watcher:
    environment:
      - EXIT_PROCESSOR_SLA_MARGIN=30
  watcher_info:
    environment:
      - EXIT_PROCESSOR_SLA_MARGIN=30
