version: "3.4"
services:

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -d -e 100000 -m "myth like bonus scare over problem client lizard pioneer submit female collect"
    ports:
      - "8545:8545"
      - "8546:8545"

  plasma-contracts:
    build:
      context: .
      dockerfile: plasma-contract.Dockerfile
    command:
      - /bin/sh
      - -c
      - |
          cd /home/node/plasma-contracts/plasma_framework
          npx truffle migrate --network local
          cd build
          echo '{"contracts":' > db.json && cat outputs.json >> db.json && echo '}' >> db.json
          npx json-server -w db.json -p 8000 -H 0.0.0.0
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - ETH_CLIENT_HOST=ganache
      - ETH_CLIENT_PORT=8545
      - MIN_EXIT_PERIOD=20
