
FROM omg-base-env AS omg-dev-env

ENV MIX_ENV=dev

ARG USER=elixir-omg
ARG UID=10000
ARG GID=10000

ARG APP_DIR=/app
ARG BUILD_DIR=/build

WORKDIR $APP_DIR

USER root

COPY . $APP_DIR
RUN mv -f $BUILD_DIR/* $APP_DIR && rm -rf $BUILD_DIR

RUN chown -R ${UID}:${GID} $APP_DIR

RUN MIX_ENV=test mix deps.get \
 && MIX_ENV=test mix deps.compile

USER $USER

ENTRYPOINT ["/bin/bash"]

