# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.
if Code.ensure_loaded?(WatcherSecurityCriticalAPI.Connection) do
  # override Tesla connection module if it exists because it's pointing to localhost
  Code.compiler_options(ignore_module_conflict: true)

  defmodule WatcherSecurityCriticalAPI.Connection do
    @moduledoc """
    Handle Tesla connections for WatcherSecurityCriticalAPI.
    """

    use Tesla

    # Add any middleware here (authentication)
    plug(Tesla.Middleware.BaseUrl, "http://localhost:7434")
    plug(Tesla.Middleware.Headers, [{"user-agent", "Elixir"}])
    plug(Tesla.Middleware.EncodeJson, engine: Poison)

    @doc """
    Configure an authless client connection

    # Returns

    Tesla.Env.client
    """
    @spec new() :: Tesla.Env.client()
    def new do
      Tesla.client([])
    end
  end
end
