# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ChildChainAPI.Api.Alarm do
  @moduledoc """
  API calls for all endpoints tagged `Alarm`.
  """

  alias ChildChainAPI.Connection
  import ChildChainAPI.RequestBuilder


  @doc """
  Provides alarms related to system memory, cpu and storage and application specific alarms.
  **Note:** Service operator alarms. 

  ## Parameters

  - connection (ChildChainAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %ChildChainAPI.Model.Map{}} on success
  {:error, info} on failure
  """
  @spec alarm_get(Tesla.Env.client, keyword()) :: {:ok, Map.t} | {:error, Tesla.Env.t}
  def alarm_get(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/alarm.get")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false},
      { 500, false}
    ])
  end
end
