# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ChildChainAPI.Api.Fees do
  @moduledoc """
  API calls for all endpoints tagged `Fees`.
  """

  alias ChildChainAPI.Connection
  import ChildChainAPI.RequestBuilder


  @doc """
  This endpoint retrieves the list of fee tokens currently supported by the childchain and the current amount needed to perform a transaction.

  ## Parameters

  - connection (ChildChainAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :fees_all_body_schema (FeesAllBodySchema): 
  ## Returns

  {:ok, %ChildChainAPI.Model.Map{}} on success
  {:error, info} on failure
  """
  @spec fees_all(Tesla.Env.client, keyword()) :: {:ok, Map.t} | {:error, Tesla.Env.t}
  def fees_all(connection, opts \\ []) do
    optional_params = %{
      :"FeesAllBodySchema" => :body
    }
    %{}
    |> method(:post)
    |> url("/fees.all")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false},
      { 500, false}
    ])
  end
end
