# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ChildChainAPI.Api.Transaction do
  @moduledoc """
  API calls for all endpoints tagged `Transaction`.
  """

  alias ChildChainAPI.Connection
  import ChildChainAPI.RequestBuilder


  @doc """
  This endpoint submits a signed transaction to the child chain.
  Normally you should call the Watcher's Transaction - Submit instead of this. The Watcher's version performs various security and validation checks before submitting the transaction, so is much safer. However, if the Watcher is not available this version exists. 

  ## Parameters

  - connection (ChildChainAPI.Connection): Connection to server
  - transaction_submit_body_schema (TransactionSubmitBodySchema): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %ChildChainAPI.Model.Map{}} on success
  {:error, info} on failure
  """
  @spec submit(Tesla.Env.client, ChildChainAPI.Model.TransactionSubmitBodySchema.t, keyword()) :: {:ok, Map.t} | {:error, Tesla.Env.t}
  def submit(connection, transaction_submit_body_schema, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/transaction.submit")
    |> add_param(:body, :body, transaction_submit_body_schema)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false},
      { 500, false}
    ])
  end
end
