# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule WatcherSecurityCriticalAPI.Api.Account do
  @moduledoc """
  API calls for all endpoints tagged `Account`.
  """

  alias WatcherSecurityCriticalAPI.Connection
  import WatcherSecurityCriticalAPI.RequestBuilder

  @doc """
  Gets all utxos belonging to the given address.
  **Note:** this is a performance intensive call and should only be used if the chain is byzantine and the user needs to retrieve utxo information to be able to exit. Normally an application should use the Informational API's [Account - Get Utxos](http://TODO) instead. This version is provided in case the Informational API is not available. 

  ## Parameters

  - connection (WatcherSecurityCriticalAPI.Connection): Connection to server
  - address_body_schema (AddressBodySchema): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %WatcherSecurityCriticalAPI.Model.Map{}} on success
  {:error, info} on failure
  """
  @spec account_get_exitable_utxos(
          Tesla.Env.client(),
          WatcherSecurityCriticalAPI.Model.AddressBodySchema.t(),
          keyword()
        ) :: {:ok, Map.t()} | {:error, Tesla.Env.t()}
  def account_get_exitable_utxos(connection, address_body_schema, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/account.get_exitable_utxos")
    |> add_param(:body, :body, address_body_schema)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      {200, false},
      {500, false}
    ])
  end
end
