# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule WatcherSecurityCriticalAPI.Api.Status do
  @moduledoc """
  API calls for all endpoints tagged `Status`.
  """

  alias WatcherSecurityCriticalAPI.Connection
  import WatcherSecurityCriticalAPI.RequestBuilder

  @doc """
  Returns information about the current state of the child chain and the watcher.
  The most critical function of the Watcher is to monitor the ChildChain and report dishonest activity. The user must call the `/status.get` endpoint periodically to check. Any situation that requires the user to either exit or challenge an invalid exit will be included in the `byzantine_events` field. 

  ## Parameters

  - connection (WatcherSecurityCriticalAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %WatcherSecurityCriticalAPI.Model.Map{}} on success
  {:error, info} on failure
  """
  @spec status_get(Tesla.Env.client(), keyword()) :: {:ok, Map.t()} | {:error, Tesla.Env.t()}
  def status_get(connection, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/status.get")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      {200, false},
      {500, false}
    ])
  end
end
