# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ChildChainAPI.Model.FeesAllBodySchema do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"currencies",
    :"tx_types"
  ]

  @type t :: %__MODULE__{
    :"currencies" => [String.t] | nil,
    :"tx_types" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: ChildChainAPI.Model.FeesAllBodySchema do
  def decode(value, _options) do
    value
  end
end

