# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ChildChainAPI.Model.TransactionSubmitBodySchema do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :transaction
  ]

  @type t :: %__MODULE__{
          :transaction => String.t()
        }
end

defimpl Poison.Decoder, for: ChildChainAPI.Model.TransactionSubmitBodySchema do
  def decode(value, _options) do
    value
  end
end
