# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule WatchersInformationalAPI.Model.TransactionCreatePayments do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :currency,
    :owner
  ]

  @type t :: %__MODULE__{
          :amount => integer(),
          :currency => String.t(),
          :owner => String.t() | nil
        }
end

defimpl Poison.Decoder, for: WatchersInformationalAPI.Model.TransactionCreatePayments do
  def decode(value, _options) do
    value
  end
end
