# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule WatchersInformationalAPI.Model.AddressBodySchema1 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :address
  ]

  @type t :: %__MODULE__{
          :address => String.t()
        }
end

defimpl Poison.Decoder, for: WatchersInformationalAPI.Model.AddressBodySchema1 do
  def decode(value, _options) do
    value
  end
end
