# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule WatchersInformationalAPI.Model.CreateTransactionsBodySchema do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :owner,
    :payments,
    :fee,
    :metadata
  ]

  @type t :: %__MODULE__{
          :owner => String.t(),
          :payments => [TransactionCreatePayments],
          :fee => TransactionCreateFee,
          :metadata => String.t() | nil
        }
end

defimpl Poison.Decoder, for: WatchersInformationalAPI.Model.CreateTransactionsBodySchema do
  import WatchersInformationalAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:payments, :list, WatchersInformationalAPI.Model.TransactionCreatePayments, options)
    |> deserialize(:fee, :struct, WatchersInformationalAPI.Model.TransactionCreateFee, options)
  end
end
