# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule WatcherSecurityCriticalAPI.Model.InFlightExitInputChallengeDataBodySchema do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :txbytes,
    :input_index
  ]

  @type t :: %__MODULE__{
          :txbytes => String.t(),
          :input_index => integer()
        }
end

defimpl Poison.Decoder, for: WatcherSecurityCriticalAPI.Model.InFlightExitInputChallengeDataBodySchema do
  def decode(value, _options) do
    value
  end
end
