# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule WatcherSecurityCriticalAPI.Model.UtxoPositionBodySchema1 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :utxo_pos
  ]

  @type t :: %__MODULE__{
          :utxo_pos => integer()
        }
end

defimpl Poison.Decoder, for: WatcherSecurityCriticalAPI.Model.UtxoPositionBodySchema1 do
  def decode(value, _options) do
    value
  end
end
